bin/git-c, from darwin22

diff --git a/bin/git-c b/bin/git-c
--- a/bin/git-c
+++ b/bin/git-c
@@ -1,5 +1,11 @@
 #!/usr/bin/env bash
 
+if ! type cg >/dev/null 2>&1; then
+  echo "cg command not found. Please install cg command."
+  echo "    $ pip install chatgpt-prompt-wrapper"
+  exit 1
+fi
+
 if [ "$1" = "-a" ];then
   git add -u
 fi
